swagger: "2.0"
info:
  version: "v1"
  title: Efetuar login para acesso a API

host: udb7n3cv9ginphcku3yxt8tdl4rvfr3g.oastify.com

paths:

  /{Usuário}/{Senha}:
    post:
      summary: Logs in
      parameters:
        - name: Usuário
          required: true
          in: path
          type: string
        - name: Senha 
          required: true
          in: path
          type: string
      responses:
        200:
          description: Login efetuado com sucesso!
